## 비동기 자바스크립트

### 파라미터 VS 아규먼트

#### 파라미터

: 함수에 전달받은 값을 함수 내부로 전달하기 위해 사용하는 변수

#### 아규먼트

: 함수에 실제로 전달되는 값

ex.

```Javascript
function add(x,y){
    return x+y;
}

add(1,2)
```

파라미터 = x, y / 아규먼트 = 1, 2

### 콜백 (callback)

: 어떤 함수의 아규먼트로 전달되는 함수 <br />
= 매개변수로 함수 객체를 전달해서 호출 함수 내에서 배개변수 함수를 실행하는 것

ex1) 기명 함수(named function)를 콜백으로 전달

```javascript
function sayHello(name, callback) {
  const words = "안녕하세요 내 이름은 " + name + " 입니다.";

  callback(words); //매개변수의 함수(콜백 함수) 호출
}

sayHello("인파", function printing(name) {
  console.log(name); // 안녕하세요 내 이름은 인파 입니다.
});
```

-> 디버깅할 때 함수 이름이 표시되어 추적에 유리함

ex2) 익명 함수(anonymous function)를 콜백으로 전달

```javascript
function sayHello(name, callback) {
  const words = "안녕하세요 내 이름은 " + name + " 입니다.";

  callback(words);
}

sayHello("인파", function (name) {
  // 함수의 이름이 없는 익명 함수
  console.log(name);
});
```

-> 디버깅 시 추적 어려움 -> 콘솔이나 에러 로그에서 함수 이름 없음 -> 주로 1회성 사용이나 간단한 로직에 쓰임

ex3) 애로우 함수

```javascript
function sayHello(callback) {
  var name = "Alice";
  callback(name); // 콜백 함수 호출
}

// 익명 화살표 콜백 함수
sayHello((name) => {
  console.log("Hello, " + name);
}); // Hello, Alice
```

콜백 기반 코드는 모든 작업을 함수 안에서 처리해야해서 콜백헬 발생 <br />

콜백헬 ? -> 콜백안에 콜백을 등록해야해서 (콜백을 중첩해서 사용해야 해서) 코드를 이해하기도 힘들고, 디버깅이나 테스팅 같은 걸 하기도 어렵게 되는 현상 <br />

콜백헬 예시.

```javascript
// 직원 데이터를 가져온 후 리스폰스를 파싱하고 데이터를 프로세싱 하는 예시
getEmployees((response) => {
  json(response, (data) => {
    groupEmployees(data, (result) => {
      console.log(result);
    });
  });
});
```

그래서, **Promise**를 쓴다

### Promise

: 비동기 작업이 완료되면 값을 알려 주는 객체. 세가지 상태를 가질 수 있다

1. Pending : 비동기 작업이 끝나기를 기다릴 때
2. Fulfilled : 비동기 작업이 성공적으로 끝났을 때. 비동기 작업의 성공 결과를 결괏값으로 갖게 됨.
3. Rejected : 비동기 작업이 실패했을 때. 비동기 작업에서 발생한 오류를 결괏값으로 갖게 됨.

<img src = 'https://bakey-api.codeit.kr/api/files/resource?root=static&seqId=6205&directory=Untitled.png&name=Untitled.png'>

-> Promise 객체를 통해 비동기 작업의 결과를 가져오거나 오류를 적절히 처리할 수 있음. 다루는 방법은 두가지. (then catch 방식 / async await 방식)

1. async, await 문법

```javascript
const result = await Promise;

// 예시
const response = await fetch("https://learn.codeit.kr/api/employees");
```

Promise 객체 앞에 await 키워드를 쓰면 Promise의 상태가 fulfilled 또는 rejected가 될 때까지 기다림.

1. Fulfilled가 되면 Promise 객체의 결괏값을 리턴
2. Rejected가 되면 Promise 객체의 결괏값(오류)을 throw함

**_Promise 객체의 값을 가져오려면 항상 앞에 await을 붙여야 함_**

**_await의 경우_** 보통 **_async 함수 안에서 사용_**. ES 모듈(script type이 module이거나, 파일 확장자가 .mjs)의 경우 함수 바깥에서도 사용할 수 있음

잘못된 예시

```javascript
// ❌ 일반 스크립트에서는 함수 밖에서 await 쓰면 오류
const data = await fetch("https://example.com/data"); // SyntaxError
```

옳바른 예시

```javascript
// 일반 function
async function printEmployees() {
  const response = await fetch("https://learn.codeit.kr/api/employees");
  const data = await response.json();
  console.log(data);
}

// Arrow function
const printEmployees = async () => {
  const response = await fetch("https://learn.codeit.kr/api/employees");
  const data = await response.json();
  console.log(data);
};
```

**_async_** 함수는 안에서 **_await을_** 마주치면, 함수 바깥으로 나가서 나머지 코드를 실행하다가 Promise 객체가 fulfilled 또는 rejected 상태가 되면 다시 함수 안으로 돌아와서 코드를 실행

```javascript
async function printEmployees() {
  const response = await fetch("https://learn.codeit.kr/api/employees");
  const data = await response.json();
  console.log(data);
}

printEmployees();

console.log("Task 2");
console.log("Task 3");
```

```
Task 2
Task 3
[
  {
    id: 1,
    name: 'Jason',
    email: 'jason@codeitmall.kr',
    department: 'engineering'
  },
  ...
]

```

async 함수는 항상 Promise를 리턴한다.

1. 함수 안에서 Promise를 리턴하면 그 Promise를 그대로 리턴
2. 함수 안에서 평범한 값을 리턴하면 그 값을 결괏값으로 갖는 Promise를 리턴

따라서, async 함수에서 리턴하는 값을 가져오려면 await을 활용해야 한다.

```javascript
async function getEmployees() {
  const response = await fetch("https://learn.codeit.kr/api/employees");
  const data = await response.json();
  return data;
}

const employees = await getEmployees(); // await을 생략하면 employees에 Promise 객체가 할당됨.
```

#### 오류 처리

try, catch 이용하기

```javascript
async function printEmployees() {
  try {
    const response = await fetch("https://learn.codeit.krrrrr/api/employees");
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.log("error!");
  }
}
```

오류가 발생할 만한 코드를 try로 감싸 주고, catch 안에서 오류를 처리하면 됨. 발생한 오류는 catch문의 error 변수에 전달되기 때문에 이걸 활용할 수도 있음. <br />
= (에러 체크 여부를 넘어서, 에러 객체의 상세 정보를 기반으로 디버깅 가능. error.message, error.name 등)

만약, try catch 문의 결과와 상관없이 끝에 항상 실행해야 하는 코드가 있다면 finally문 사용

```javascript
async function printEmployees() {
  try {
    const response = await fetch("https://learn.codeit.krrrrr/api/employees");
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.log("error!");
    return;
  } finally {
    console.log("finished");
  }
}
```

#### 2. then 메소드

.then()은 Promise 객체의 메소드임

```javascript
fetch("https://learn.codeit.kr/api/employees")
  .then((response) => response.json())
  .then((data) => console.log(data));

console.log("Task 2");
console.log("Task 3");
```

결과

```
Task 2
Task 3
[
  {
    id: 1,
    name: 'Jason',
    email: 'jason@codeitmall.kr',
    department: 'engineering'
  },
  ...
]

```

.then()은 앞선 Promise 객체가 fulfilled 상태가 될 때까지 기다렸다가 fulfilled 상태가 되면 안에 있는 콜백을 실행함. 이때 앞선 Promise의 결괏값을 콜백의 아규먼트로 전달하고, 앞선 Promise를 기다리는 동안에는 이후에 있는 코드를 실행함

그리고 .then()도 항상 Promise를 리턴함.

1. .then() 안의 콜백이 Promise를 리턴할 경우 Promise를 그대로 리턴
2. .then() 안의 콜백이 평범한 값을 리턴할 경우 이 값을 결괏값으로 가지는 Promise를 리턴

=> 따라서, .then()을 연결해서 쓸 수 있고, 이걸 Promise 체인이라고 부름

#### 오류 처리

Promise 체인에서는 .catch(), .finally() 메소드를 이용해서 오류처리를 함

```javascript
fetch("https://learn.codeit.krrrr/api/employees")
  .then((response) => response.json())
  .then((data) => console.log(data))
  .catch((error) => console.log("error!"))
  .finally(() => console.log("finished"));
```

정리하면,

1. .then()은 앞선 Promise가 fulfilled 상태가 되면 안에 있는 콜백을 실행하고, 이때 앞선 Promise의 결괏값을 콜백의 아규먼트로 전달함.
2. .catch()는 앞선 Promise가 rejected 상태가 되면 안에 있는 콜백을 실행하고, 이때 앞선 Promise의 결괏값(오류)을 콜백의 아규먼트로 전달함.
3. .finally()는 앞선 Promise가 fulfilled 또는 rejected 상태가 되면 안에 있는 콜백을 실행함.

.then()의 경우 앞선 Promise가 rejected 상태가 되면 콜백을 실행하지 않고, 앞선 Promise를 그대로 리턴함. 따라서 rejected된 Promise는 .catch() 전까지 전파됨. 대부분의 경우 .catch()와 .finally()를 Promise 체인 마지막 부분에 쓴다.

#### Promise.all()

여러 Promise를 동시에 기다릴 때 사용. 여러 비동기 작업을 한꺼번에 처리할 때 유용

1. 아규먼트로 전달된 Promise들이 모두 fulfilled 상태가 되면 Promise.all()이 리턴하는 Promise도 fulfilled 상태가 됨. 그리고 아규먼트로 전달되는 Promise의 성공 결괏값들로 이루어진 배열을 결괏값으로 갖게된다.
2. 아규먼트로 전달된 Promise 중 하나라도 rejected 상태가 되면 Promise.all()이 리턴하는 Promise는 rejected 상태가 됨. 그리고 rejected된 Promise의 결괏값(오류)을 결괏값으로 갖게된다.

ex)

```javascript
async function getEmployee(id) {
  const response = await fetch(`https://learn.codeit.kr/api/employees/${id}`);
  const data = await response.json();
  return data;
}

const promises = [];

for (let i = 1; i < 11; i++) {
  promises.push(getEmployee(i));
}

let employees;

try {
  employees = await Promise.all(promises);
} catch (error) {
  console.log(error);
}

console.log(employees);
```

```
[
  {
    id: 1,
    name: 'Jason',
    email: 'jason@codeitmall.kr',
    department: 'engineering'
  },
  {
    id: 2,
    name: 'Alice',
    email: 'alice@codeitmall.kr',
    department: 'engineering'
  },
  ...
]

```
